worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name intern-1.it-all-stars.com;

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name intern-1.it-all-stars.com;
        
        ssl_certificate /etc/letsencrypt/live/intern-1.it-all-stars.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/intern-1.it-all-stars.com/privkey.pem;

        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://go-api:8000;
        }

        location / {
            proxy_pass http://nextjs:3000;
        }
    }
}